name: Deploy Shiny App

on:
  push:
    branches: [ main ]
    paths:
      - "app.R"
      - "www/**"
      - "R/**"
      - "data/**"
      - ".github/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rsconnect

      - name: Deploy to shinyapps.io
        run: |
          R -e "rsconnect::setAccountInfo(
                  name='${{ secrets.SHINYAPPS_NAME }}',
                  token='${{ secrets.SHINYAPPS_TOKEN }}',
                  secret='${{ secrets.SHINYAPPS_SECRET }}'
                )"
          R -e "rsconnect::deployApp('.', appName='tictac-montecarlo',  forceUpdate = TRUE)"
